### ISSUE TITLE
Implement curved sections with background images

### ISSUE THREAD

**Issue by n4itik** [n4itik/Huddle#1]
**Description:**

The curved sections on the webpage are currently constructed using a combination of images and background colors.

**Expected Behavior:**

Find a solution that allows for the use of background-images in CSS without compromising the established layout.

**Additional Context:**
- The current implementation involves using full-width images within the HTML for the curved sections.
- There are 5 such images for desktop view and 5 for mobile view.

**Screenshot:**

![desktop-footer](https://github.com/n4itik/Huddle/assets/66974007/2d950ad9-87e5-4e9b-a4e3-1a97d16bb74f)

**Comment by adisuyash** [comment]
I would like to work on this issue.
Please assign it to me.
